### ISSUE TITLE
Mysql Connection from host machine. Unable to connect 'reading initial communication packet', system error: 0

### ISSUE THREAD

**Issue by AntonioCS** [phpdocker-io/phpdocker.io#120]
Hey,

I know you have this issue: 
- https://github.com/phpdocker-io/phpdocker.io/issues/68

regarding connecting to mysql but I am unable to use that as a solution.
This is my docker-compose.yml:

> 
> services:
> 
>     mysql:
>       image: mysql:8.0
>       container_name: sugarcrm-mysql
>       working_dir: /application
>       volumes:
>         - ./SugarCE-Full-6.5.26/:/application
>       environment:
>         - MYSQL_ROOT_PASSWORD=admin
>         - MYSQL_DATABASE=sugarcrm
>         - MYSQL_USER=sugar
>         - MYSQL_PASSWORD=sugar
>       ports:
>        - "3351:3336"
> 
>     webserver:
>       image: nginx:alpine
>       container_name: sugarcrm-webserver
>       working_dir: /application
>       volumes:
>           - ./SugarCE-Full-6.5.26/:/application
>           - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
>       ports:
>        - "8080:80"
> 
>     php-fpm:
>       build: phpdocker/php-fpm
>       container_name: sugarcrm-php-fpm
>       working_dir: /application
>       volumes:
>         - ./SugarCE-Full-6.5.26/:/application
>         - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

Every time I connect I get the following error:

> Lost connection to MySQL server at 'reading initial communication packet', system error: 0

This happens for the root and the sugar user.

I have not changed my.cnf file. 
Has anyone ran into this issue?? Any way to fix this? I really need to connect to mysql from my host machine.

Thanks!

**Comment by luispabon** [comment]
Try switching to `mysql:5.7` from `mysql:8.0`

**Comment by AntonioCS** [comment]
@luispabon Just tried that and I got the same error. I believe this is some configuration that I am missing.

In a vagrant machine I would connect to mysql via ssh and would never have any issues but now I have switched to docker and really need to connect to mysql from my host machine.

Anyone?

**Comment by luispabon** [comment]
@AntonioCS you're not missing anything, I can connect just fine from mysql-cli from my host into your development environment, and also phpstorm's schema tool.

Are you connecting to the right port as per your config (3351)?

**Comment by AntonioCS** [comment]
@luispabon Sorry for the delay. 
Yes I am sure I am using the right config.

Here is a screenshot from the session manager in heidisql
![2017_08_10_15_43_23_mysql_connection_from_host_machine _unable_to_connect_reading_initial_communica](https://user-images.githubusercontent.com/1086401/29176251-38be5294-7de3-11e7-8d15-b3db9d0ecfe8.png)

What other settings can I use? You can see there the error I get when I try to connect.

**Comment by AntonioCS** [comment]
Ok, found the issue.
I was mapping to the wrong port.
You can see there in the yml file:

- "3351:3336"

Should be:

"3351:3306"

Ops!

**Comment by luispabon** [comment]
d'oh!
