### ISSUE TITLE
specific network pamater

### ISSUE THREAD

**Issue by shiroamada** [phpdocker-io/phpdocker.io#121]
Hi,
How do I able to set custom bridge IP in your docker-compose.yml

below is the docker command if I run in single container.
`docker run --rm -it -v /vagrant_data/:/var/www/html --net shared_nw --ip 192.168.33.11 php71`

What is the setup I need to done in docker-compose.yml file?

Below is the setting I set in my docker file, I follow this tutorial.
https://coderwall.com/p/2rpbba/docker-create-a-bridge-and-shared-network

**Comment by luispabon** [comment]
Shiro, please check docker-compose's documentation on networking, particularly adding custom networks:

https://docs.docker.com/compose/networking/#specifying-custom-networks

Hope this helps.

This isn't really a phpdocker.io issue, so closing.
