### ISSUE TITLE
Remove base port limit

### ISSUE THREAD

**Issue by AntonioCS** [phpdocker-io/phpdocker.io#123]
Hey,

I am working on a legacy application and setting the webserver port to 80 is a requirement.
What I did was set the base port to 8080 and then change it to 80 but I was just wondering why do I get this error: 
- This value should be "1025" or more.

If I set it to 80. What is the issue?

**Comment by luispabon** [comment]
It's a safety measure to avoid clashes with services running on your computer. Typically you'd also need root to open any port below 1024, although this doesn't apply as docker would be doing it on your behalf. 

It's up to you to tweak your docker-compose file further :+1:

**Comment by AntonioCS** [comment]
@luispabon Still doesn't make sense to have something preventing me from doing it in the UI, but ok
