### ISSUE TITLE
Error_log directive in nginx.conf. Why?

### ISSUE THREAD

**Issue by AntonioCS** [phpdocker-io/phpdocker.io#125]
Is there any reason the nginx conf has this:

>  fastcgi_param PHP_VALUE "error_log=/var/log/nginx/application_php_errors.log";

I thought I was doing something wrong in the php-ini-overrides.ini file but then I thought of checking the nginx.conf and there it was the setting I wanted to change in the ini file.

**Comment by luispabon** [comment]
What trouble is it causing you? All your errors should still be coming out of stdout into the container logs.

**Comment by AntonioCS** [comment]
Does it make sense to have that there?
I am trying to debug why I have a fatal error showing in the server but not showing up on my local machine.

The server is not using docker it's just an aws instance, but the code is exactly the same.
I have 
```
display_errors = On
error_log =/application/php-error.log
```
On the override ini but I am still not seeing anything. (not even on the log file)
The page is displaying the same as it is on the server but without the fatal error msg.

This is extremely frustrating.
In the php I have put
```
   error_reporting( E_ALL );
    ini_set( "display_errors", 1 );
    ini_set( "error_reporting", 1 );
```

And still nothing. Is there somewhere else the error display functions are overridden?

**Comment by luispabon** [comment]
It does. PHP errors should bubble up on stdout of the PHP container, not on the nginx container - remember, separation of concerns. This is why PHP errors are being redirected out of the way at nginx, so that only pure nginx logs show up.

This is not swallowing your errors, something else is. Have you restarted PHP-FPM to apply your ini changes? Do you have an error handler registered in your code?

**Comment by luispabon** [comment]
Bear in mind also that many of these settings are optimised for usage in docker envs (eg swarm, compose, kubernetes) - logging for instance must come out of stdout and must be of the container itself. These are container best practices.

If you're running on bare metal, you need to update your config accordingly to your requirements in there.

**Comment by AntonioCS** [comment]
I have restarted and like I said the server is running the same version of the code. So if there was an error handler it would prevent the display of the error there as well.

> It does. PHP errors should bubble up on stdout of the PHP container, not on the nginx container - remember, separation of concerns. This is why PHP errors are being redirected out of the way at nginx, so that only pure nginx logs show up.

Not following you here. What does showing php fatal errors on the page have to do with separating concerns? I am seeing php-fpm container output, the error isn't there either, but the page is still not displaying.

This is a legacy application. I am trying to dockerize it on my machine so that in the future we can dockerize it everywhere.

**Comment by luispabon** [comment]
Separation of concerns means PHP errors are handled at PHP-FPM. It has its own logging. Relying on the webserver for application logs is bad practice - it's not nginx running your code.

**Comment by AntonioCS** [comment]
Yes I know. So why is the php_ini setting on nginx?

**Comment by AntonioCS** [comment]
Not error in docker stuff. Apologies!

**Comment by luispabon** [comment]
:+1:
