### ISSUE TITLE
Apache support (FPM/FCGI)

### ISSUE THREAD

**Issue by luispabon** [phpdocker-io/phpdocker.io#129]
Users have been requesting the option of apache over nginx for a while now.

This tracks refactoring to allow for an apache/fpm (not mod_php) setup.

  * Enable users to switch between nginx (current) and apache at the generator
  * Apache config must follow nginx on framework compatibility - this is actually where the bulk of the work is expected to be
  * Implement as FPM/FCGI (not `mod_php`)
  * Allow .htaccess - this has also been requested a lot

**Comment by dugajean** [comment]
Nothing on this yet? I'd love to be able to have Apache available.

**Comment by luispabon** [comment]
Basically I never could get around doing this as I don't have a lot of time in general and very few people has ever asked for it. If you could contribute a PR I would be more than happy to accomodate.

**Comment by dugajean** [comment]
@luispabon I really would, the issue is that I'm clueless on how to do it due to my docker inexperience (I'm using your tool to help me). If you could get around to doing this sometime soon that'd be great. I apologize for not being of any help.

**Comment by luispabon** [comment]
No apologies necessary, it's good that people help in whichever way they can, whether it's reports or PRs.
