### ISSUE TITLE
UI: re-style website

### ISSUE THREAD

**Issue by luispabon** [phpdocker-io/phpdocker.io#142]
The current design is more than a bit crap, visually, and it's starting to look dated now.

**Comment by rafael-franca** [comment]
@luispabon I like to help you with the UI of v2.0. I think we should rebuild using TailwindCSS. What do you think?

Let me know what do you think.

**Comment by luispabon** [comment]
Hey @rafael-franca. I'm working on the next version of the site which right now is using Semantic UI and React in the frontend side of things. Only the generator is partially working at the moment, but it is functional. You can checkout the [next](https://github.com/phpdocker-io/phpdocker.io/tree/next) branch, then run `make init` to get the dev env up and running.
