### ISSUE TITLE
lets encrypt integration 

### ISSUE THREAD

**Issue by AntonioCS** [phpdocker-io/phpdocker.io#148]
Hey,

I have the need to launch a website that will use https. 
From my quick research the easiest way is to use certbot from letsencrypt.org.
I am going to try and integrate this in my projects setup (maybe use this as a guide https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion) but it would be cool if this could be done from the generator.

Not sure if it would be simple but I believe every site needs https these days :)

**Comment by luispabon** [comment]
If you could send over your set up once you're done I can have a go at adding it to phpdocker.io :+1: :)

**Comment by luispabon** [comment]
#205
