### ISSUE TITLE
How do I connect to the postgres container? 

### ISSUE THREAD

**Issue by brunoreis** [phpdocker-io/phpdocker.io#150]
I used phpdocker.io and generated my 3 containers. The postgres container is showing "5432/tcp" on it. How can I connect into that container from the php one (from my app)? 

* thanks for this project. 
** I'm a newbie to docker

**Comment by brunoreis** [comment]
Just figured out: I just have to set the container name as the domain on the connection url: 
"...@postgres:5432/..."

**Comment by luispabon** [comment]
No problemo. That information and other instructions are in the README within the `phpdocker` folder.
