### ISSUE TITLE
How to run this application?

### ISSUE THREAD

**Issue by dzschille** [phpdocker-io/phpdocker.io#152]
I followed the [Running the project](https://github.com/phpdocker-io/phpdocker.io#running-the-project) steps. But when i open http://localhost:10000/ or http://localhost:10000/generator i get a HTTP error code 500.

In the webserver container i only see the error code in the log:
```
172.20.0.1 - - [09/Feb/2018:21:12:48 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (X11; Ubuntu; L
inux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
172.20.0.1 - - [09/Feb/2018:21:13:04 +0000] "GET /generator HTTP/1.1" 500 5 "-" "Mozilla/5.0 (X11; 
Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
```
But i can not found more informations about this error. I can not find a php error log, neither in the php-fpm container (/var/log) nor in the project folder in var/logs.

What can be the reason for the 500?

**Comment by luispabon** [comment]
This is usually caused by non-writable `var/` folder, try

```
rm var/* -rf
sudo chmod 777 var
```

**Comment by luispabon** [comment]
The webserver container will only have nginx errors, what do you get when you run `docker-compose logs -f php-fpm` ?

You should see something like this:

![image](https://user-images.githubusercontent.com/6388823/36307179-d7adafde-1312-11e8-91af-d7fe807117e2.png)

**Comment by luispabon** [comment]
I've made a script to bootstrap the app for localdev, should help with your problem. Simply update to latest master and run the `./prepare-dev.sh` script on the root of the project. Please let me know how it goes.

**Comment by dzschille** [comment]
@luispabon thanks for your effort, i will check it this weekend.
