### ISSUE TITLE
Allow www-data to write on system

### ISSUE THREAD

**Issue by Mondane** [phpdocker-io/phpdocker.io#154]
Running a symfony 3 site will give errors concerning the symfony var folder like:

> The directory "/application/var/cache/dev/annotations" is not writable.

When logging in to the shell and looking at the permissions, it's like this:

> drwxrwxr-x  5 1000 1000    4096 Oct 28 11:51 var/

I gave the logs subfolder **chmod o+w var/logs** from the shell so it looks like:

> drwxrwxrwx 2 1000 1000  4096 Feb 27 19:15 logs/

Now, the webserver is able to add a log, which is written as:

> -rw-r--r-- 1 www-data www-data 43823 Feb 27 19:29 dev.log

As you can see, the webserver runs as www-data, which as a different uid then the data-owner (1000). Wouldn't it be possible to 
- setup the webserver docker so the www-data user has that same uid? 
- Or add a mapping or something?
- Or add the www-data to the same user group?
- etc.

The workaround I use now, is to create the var folder and perform 'chgrp www-data && chmod g+w' on it

**Comment by luispabon** [comment]
Thanks for the report. Unfortunately this permissions mismatch is hard to fix on docker (and before that in vagrant) because of the way symfony operates its cache, and how it's generated as well. Our base images have a uuid trick precisely to help with this, but it only works a) on linux systems and b) if your user was the first created (uid 1000). MacOS uses a completely different range of uids and this solution breaks down.

You could try adding the following on the php container's Dockerfile:

```Dockerfile
# File permissions workaround
RUN usermod -u 1000 www-data
```

Where 1000 is the uid on your host system, modify as necessary.

**Comment by Mondane** [comment]
mm. I just looked at my passwd and the user on my host also has uid 1000. On the php-fpm docker though, no such uid seems to be available. Could this lead to this problem?

Contents of root@2097827e3e66:/application# cat /etc/passwd
```
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
systemd-timesync:x:100:102:systemd Time Synchronization,,,:/run/systemd:/bin/false
systemd-network:x:101:103:systemd Network Management,,,:/run/systemd/netif:/bin/false
systemd-resolve:x:102:104:systemd Resolver,,,:/run/systemd/resolve:/bin/false
systemd-bus-proxy:x:103:105:systemd Bus Proxy,,,:/run/systemd:/bin/false
_apt:x:104:65534::/nonexistent:/bin/false
```

Looking further, also the webserver docker doesn't have a user with uid 1000:

/application # cat /etc/passwd
```
root:x:0:0:root:/root:/bin/ash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
operator:x:11:0:operator:/root:/bin/sh
man:x:13:15:man:/usr/man:/sbin/nologin
postmaster:x:14:12:postmaster:/var/spool/mail:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
postgres:x:70:70::/var/lib/postgresql:/bin/sh
cyrus:x:85:12::/usr/cyrus:/sbin/nologin
vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
nginx:x:100:101:Linux User,,,:/var/cache/nginx:/sbin/nologin
```
