### ISSUE TITLE
[BUG] chown has wrong order of parameters 

### ISSUE THREAD

**Issue by tomasnorre** [phpdocker-io/phpdocker.io#155]
When running the `$ prepare-dev.sh` I get the following error on OSX:

```
chown: -Rf: No such file or directory
```

This is due to wrong order of the parameters, Recursive force parameter has to go after the chown and not at the end of line.

The same goes for the lines:
``` 
sudo rm -Rf var/* -Rf
rm src/AppBundle/Resources/public/vendor/* -Rf
```

**Comment by luispabon** [comment]
Closed
