### ISSUE TITLE
php7.2-bcmath doesn't get installed on phpdockerio/php72-fpm:latest

### ISSUE THREAD

**Issue by LaPelle** [phpdocker-io/phpdocker.io#163]
After running `docker-compose up -d` everything seems to work except for the bcmath module, which doesn't get installed.

I checked if the module gets loaded by running `docker-compose exec php-fpm php -m` and bcmath is not listed.

It is supposed to install the module as it is present in the `apt-get install`line in `php-fpm/Dockerfile`

```Dockerfile
RUN apt-get update \
    && apt-get -y --no-install-recommends install php7.2-mysql php-redis php-xdebug php7.2-bcmath
```

**Comment by luispabon** [comment]
@LaPelle mmm just checked and everything seems in order:

```
root@3ffdae34ecdd:/workdir# apt-get update \
>     && apt-get -y --no-install-recommends install php7.2-mysql php-redis php-xdebug php7.2-bcmath

[...]

The following NEW packages will be installed:
  php-igbinary php-redis php-xdebug php7.2-bcmath php7.2-mysql

[...]

root@3ffdae34ecdd:/workdir# php -m|grep bcm
bcmath
root@3ffdae34ecdd:/workdir# php -i|grep bcm
/etc/php/7.2/cli/conf.d/20-bcmath.ini,
bcmath
bcmath.scale => 0 => 0
```

**Comment by LaPelle** [comment]
After I manually update the container with `apt-get update` and then manually try to install with `apt-get -y --no-install-recommends install 7.2-bcmath` it does get installed.

**Comment by luispabon** [comment]
Hmm I know what happened. There was a string of build issues at docker hub that prevented the latest php version to be built correctly, thus making the OS base outdated and in need of apt dist-upgrade, which would would make certain apt operations to fail silently. I'm triggering a manual build right now see if the issues persist (issues were at docker hub, not at the Dockerfile).

**Comment by LaPelle** [comment]
Sorry, I was away for a few weeks. I'm not able to test it right now, but will soon.

**Comment by LaPelle** [comment]
Seems to work now, thank you.
