### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by luispabon** [phpdocker-io/phpdocker.io#164]
This is to track progress of php 7.3 support:

- [x] CLI and FPM base images - closed at https://github.com/phpdocker-io/base-images/pull/20
- [x] CI setup - set up at https://ci.auronconsulting.co.uk/teams/main/pipelines/phpdocker-base-images/jobs/php%207.3
- [x] Docker hub setup - images available at `phpdockerio/php73-cli` and `phpdockerio/php73-fpm`
- [ ] Website support

**Comment by do-web** [comment]
Not working:

[error] 9#9: *6 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.23.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.23.0.2:9000",

**Comment by luispabon** [comment]
So what seems to be happening here is that the favicon request is being passed on to php-fpm and it's perhaps crashing, if trying to execute the file that's there. The nginx config isn't quite right. Which option did you choose on the "framework" select?

**Comment by xtfs** [comment]
@luispabon same problem here, i choose the symfony, laravel... Option on the framework.

502 Bad Gateway returned.

**Comment by luispabon** [comment]
Do you guys have a repository I can check out?

**Comment by xtfs** [comment]
> 
> 
> Do you guys have a repository I can check out?

Yes, check this repo: https://github.com/xtfs/phpdocker-sf4-nginx

**Comment by luispabon** [comment]
Thank you. Hmm this is interesting:

```
carry-php-fpm | [28-Jan-2019 13:17:09] WARNING: [pool www] child 12 exited on signal 11 (SIGSEGV - core dumped) after 27.732746 seconds from start
carry-php-fpm | [28-Jan-2019 13:17:09] NOTICE: [pool www] child 14 started
```

I wonder if it's a dodgy extension.

**Comment by luispabon** [comment]
You can track https://github.com/phpdocker-io/phpdocker.io/issues/180 instead

**Comment by xtfs** [comment]
Of course, I removed the xdebug and tested, worked fine. Thanks @luispabon

**Comment by luispabon** [comment]
no problemo, thank you for your help. If you subscribe to #180 above you'll know once you can re-enable xdebug in your project.
