### ISSUE TITLE
Composer complaining about unzip

### ISSUE THREAD

**Issue by AntonioCS** [phpdocker-io/phpdocker.io#178]
Hey,

I am running a container with php5.6 and when I run `composer install` I get the following:
```
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
```
I can add this to the container (via the php dockerfile) but maybe this can be added by default?
Or is there any reason why this should not be included?

**Comment by luispabon** [comment]
Apologies, I forgot to close this. Base images do contain unzip for a while now.
