### ISSUE TITLE
mailhog setup

### ISSUE THREAD

**Issue by AntonioCS** [phpdocker-io/phpdocker.io#179]
Hey guys,

How exactly is mailhog suppose to be configured with the php container? The php container does not have sendmail installed so how exactly is the mail() function suppose to send the mails to mailhog?

I have mails failing and not sure how to fix this. I have tried installing sendmail and using that but then I get a timeout every time I use the mail() function.

Anyone have any ideas?

**Comment by AntonioCS** [comment]
Seems something like [nullmailler](http://untroubled.org/nullmailer/) will have to be used if you only use the mail() function.

Maybe if possible you can add something on the web ui to add and configure this on the php-fpm container.

I will try to set this all up

**Comment by luispabon** [comment]
mail() as far as I can tell will attempt to use sendmail, which will require setting up postfix or similar locally. Mailhog however won't accept anything other than SMTP. On the generated readme you should have connection details for mailhog.

It's an implementation detail on your app really but I would advise against using mail directly and instead use one of the many third party libs available (eg swiftmailer) that come with swappable mail transports (sendmail, smtp, mailgun etc).

**Comment by AntonioCS** [comment]
@luispabon working on legacy app there is no way I will be authorised to make such a change, but I completely agree with you

**Comment by luispabon** [comment]
What framework are you using, if any? Symfony and Laravel both have a mail collection feature for localdev that require no external system dependencies beyond their own mailer packages.
