### ISSUE TITLE
XDebug crashes php 7.3

### ISSUE THREAD

**Issue by luispabon** [phpdocker-io/phpdocker.io#180]
As per title, chasing to see what it is. Will remove from generator temporarily.

**Comment by luispabon** [comment]
It's actually a bug in upstream PHP 7.3.0 and PHP 7.3.1's opcache:

https://bugs.php.net/bug.php?id=77287

**Comment by luispabon** [comment]
I'm deploying the branch above to prod and will re-deploy master as soon as I confirm php 7.3.2 is out and xdebug doesn't crash.

**Comment by luispabon** [comment]
Re-enabled.

**Comment by luizjr** [comment]
Hi @luispabon, I need a guide for setting up xDebug on VSCode using php7.3-fpm

I haven't found anything explaining with this version yet.
