### ISSUE TITLE
Add support for PostGIS (PostgreSQL  extender)

### ISSUE THREAD

**Issue by maciejsk** [phpdocker-io/phpdocker.io#187]
PostGIS is a spatial database extender for PostgreSQL object-relational database. It adds support for geographic objects allowing location queries to be run in SQL.

**Comment by luispabon** [comment]
@maciejsk good shout. At the moment, postgis is only available in alpine at their edge version, which at some point will be the base for postgres alpine images.

In the meantime, you can change your env by removing "-alpine" from the postgres image name. These are based on debian stretch, and you can easily install postgis for your version of postgres via apt-get.
