### ISSUE TITLE
Debian Wheezy and Jessie (except LTS) removed from mirrors (php56-fpm:latest)

### ISSUE THREAD

**Issue by LeafarDev** [phpdocker-io/phpdocker.io#189]
Wheezy and Jessie were [recently removed](https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html) from the mirror network. Is there a possibility to change to the Debian Long Term Support (LTS)?
Tip: The **insecure** way to workaround this issue:

> RUN echo 'Acquire::Check-Valid-Until "0";' > /etc/apt/apt.conf.d/10no--check-valid-until
RUN echo "\
deb http://cdn-fastly.deb.debian.org/debian/ jessie main \n\
deb http://security.debian.org/ jessie/updates main \n\
deb http://archive.debian.org/debian jessie-backports main \
" > /etc/apt/sources.list

**Comment by luispabon** [comment]
@LeafarDev as far as I understand it, Jessie is still LTS for amd64 until [https://wiki.debian.org/LTS/](end of june next year). We're currently using standard jessie packagages and archives as provided by their base image. Is this caising you any problems?
