### ISSUE TITLE
why base on own phpdockerio/php73-fpm ?

### ISSUE THREAD

**Issue by blafasel42** [phpdocker-io/phpdocker.io#190]
When you already generate Dockerfiles, why base on own base image? Why not base on PHP standard image or maybe on alpine or ubuntu base image?

**Comment by blafasel42** [comment]
Or to make it like a feature request: How about making Base image configurable?

**Comment by luispabon** [comment]
You can read the rationale on this interview I gave some time ago:

https://www.shiphp.com/blog/2017/luis-pabon-phpdockerio
