### ISSUE TITLE
Manual for enabling Xdebug would be helpful

### ISSUE THREAD

**Issue by thomasg87** [phpdocker-io/phpdocker.io#192]

**Comment by luispabon** [comment]
#204

**Comment by JohnKlein1991** [comment]
@luispabon 
Hi! I prepared a manual about debugging with XDebug and PHPStorm. Please, check this https://docs.google.com/document/d/1ws1rURo0T9ZRfEfMIQWnCd-U5Q0PZwpRp_wH5ZSwDM0/edit?usp=sharing
Is it good enough or not?

**Comment by luispabon** [comment]
Thank you John, I can use this :+1:

**Comment by JohnKlein1991** [comment]
Ok. Do I need to make the pull request?

**Comment by luispabon** [comment]
If you could, that'd be gr8.

**Comment by scwall** [comment]
add for windows in php-ini-overrides.ini
xdebug.remote_host = host.docker.internal

**Comment by scwall** [comment]
# New parameter for timeout 
## nginx.conf
fastcgi_read_timeout 90000;
## php-ini-overrides.ini
max_execution_time = 0

**Comment by JohnKlein1991** [comment]
@luispabon created pull request: https://github.com/phpdocker-io/phpdocker.io/pull/235

**Comment by luispabon** [comment]
Closed via #235
