### ISSUE TITLE
Speed up shutdown of php-fpm container via docker-compose down

### ISSUE THREAD

**Issue by tobiasmuehl** [phpdocker-io/phpdocker.io#209]
Compared to other dockerfiles the ones generated from this repo take a long time to shut down. 

```sh
docker-compose up -d
docker-compose down # takes up to 10 seconds for php-fpm to stop
```

Couldn't find out which option/flag to set to speed this up - any ideas?

**Comment by luispabon** [comment]
I suspect the `process_control_timeout` directive for php-fpm has different values on the official php images vs debian packaged ones. The default value according to docs is 0. I'll have a look.

**Comment by luispabon** [comment]
Looks like for some reason the fpm process is launched via `sh -c` even though the entry point is null. Therefore the stop signal goes to sh and not fpm. The reason it's taking 10s is because it's in fact timing out at which point docker nukes it from orbit. Trying to get to the bottom of it.

**Comment by luispabon** [comment]
So sh and bash both swallow any SIG*** signals. We do need at the moment bash or sh to correctly run the sed filter that strips out a lot of crap fpm adds to its own stdout (eg your logs come out this way and would get polluted by it). Looking at ways around this.

**Comment by luispabon** [comment]
@tobiasmuehl this is now fixed in php 7.3. Thankfully they added `decorate_workers_output` to fpm's config that does the same thing the `sed` workaround did. This however is not available on php 7.2 and below. Which version are you using?

**Comment by tobiasmuehl** [comment]
@luispabon Thanks for the quick reply and sorry for the slow reply on my part. I'm on 7.3, so replacing `sed` for `decorate_workers_output` is entirely possible for my usecase.

**Comment by luispabon** [comment]
It's all fixed on the base image, just pull and rebuild

**Comment by tobiasmuehl** [comment]
Can confirm. Excellent!

**Comment by luispabon** [comment]
Great stuff, thanks for reporting :+1:
