### ISSUE TITLE
Add msgpack extension

### ISSUE THREAD

**Issue by tobiasmuehl** [phpdocker-io/phpdocker.io#211]
https://github.com/msgpack/msgpack-php

Available in the apt repos as `php-msgpack` (note, no PHP version number)

**Comment by luispabon** [comment]
The extension is on the generator, isn't it working for you? look for "pack"

**Comment by tobiasmuehl** [comment]
Ah, I was searching for msgpack, not "messagepack"

**Comment by luispabon** [comment]
Hmmm on their site they refer to it as both `messagepack` and `msgpack`. Probs worth adding both into the name so that filtering works.

**Comment by luispabon** [comment]
Done. Should get released in the next few minutes. Thanks for reporting :+1:
