### ISSUE TITLE
web is broken

### ISSUE THREAD

**Issue by Fraitomas** [phpdocker-io/phpdocker.io#213]
https://phpdocker.io is broken
It always return 500 error
I can only see generator view but throws another 500 when press generate button

I can not been able to contact by another method because contact form is broken too

I and my colleagues really appreciate this tool
Thanks in advance

**Comment by luispabon** [comment]
@Fraitomas thanks for reporting, looks like an update went through and the fpm service didn't restart, causing all sorts of errors in the backend. Site is now back up and running.

Thank you!
