### ISSUE TITLE
Step 2/4 : WORKDIR "/application" ERROR: Service 'php-fpm' failed to build: Invalid signal: SIGQUIT

### ISSUE THREAD

**Issue by ameeno** [phpdocker-io/phpdocker.io#214]
Step 2/4 : WORKDIR "/application"
ERROR: Service 'php-fpm' failed to build: Invalid signal: SIGQUIT

thats the errors i keep getting.

zero mods just  agenerated phpdocker file.

I am using Docker for windows (Desktop) with LCOW.

i have tried under ubuntu-wsl incase it is a permissions issue but i dunno.

the message is cryptic, shouldnt the /application WD be present INSIDE the container?

**Comment by luispabon** [comment]
So you're asking two different things here. The workdir thing is a red herring.

SIGQUIT is a posix thing, it's one of a group of signals that can be sent to running processes to control whether they pause or stop or whatever. This is mostly a linux/unix thing. I'm not sure how docker for windows works but looks to me like there's something dodgy with it on your system. Docker for mac sometimes has weird "this should never happen" sort of errors that go away using its "factory reset" option.

To answer your other question, no, the workdir doesn't need to pre-exist. Docker will make sure it's there once you declare it with the workdir directive.

**Comment by ameeno** [comment]
Thanks for the clarity,

I think something is funky with the volume mounts between windows and Linux docker.


I have tried to isolate the issue by using docker-compose under WSL ubuntu (docker host forwarded via localport 2375)

clearly theres something strange going on, I will report back if i fix it.

**Comment by luispabon** [comment]
No worries.

I wouldn't be surprised, to be fair. I had to use a mac for a while last year and had all sorts of little issues with docker for mac very likely derived from bugs on the way docker is linking the virtual machine that actually runs linux and docker with the host os.

Have you tried running a vm yourself to discard docker for windows fuckery? Vagrantfile below - I always have this handy for situations when I'm not using desktop linux. 

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.10.10"

  config.vm.synced_folder "./kube", "/home/vagrant/.kube"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    # Install the basics
    apt-get update
    apt-get dist-upgrade -y
    apt-get install -y \
        ca-certificates \
        curl \
        make \
        fish \
        htop \
        ifupdown2

    # Set up shell
    cd /tmp
    chsh -s /usr/bin/fish vagrant
    curl -o omf.fish -sS -L https://get.oh-my.fish
    su vagrant -c "fish omf.fish --noninteractive" || echo "[ OMF already installed ]"
    rm omf.fish

    # Add kubectl
    snap install kubectl --classic || echo "[ kubectl already installed ]"

    # Add gcloud
    snap install google-cloud-sdk --classic || echo "[ gcloud already installed ]"

    # Set up ssh keys
    cp /vagrant/ssh/id_rsa* /home/vagrant/.ssh -f || echo "[ ssh keys already present ]"
    chmod 600 /home/vagrant/.ssh/*
    chown vagrant:vagrant /home/vagrant/.ssh/*

    # Set up shell config
    cp /vagrant/shell/*.fish /home/vagrant/.config/fish/conf.d/ -f || echo "[ Shell config already present ]"
    chown -Rf vagrant:vagrant /home/vagrant/.config/*

    # Add and setup docker
    snap install docker || echo "[ Docker already installed ]"
    groupadd docker || echo "[ Docker group already present ]"
    usermod -aG docker vagrant || echo "[ User already belongs to the docker group ]"
  SHELL
end
```

**Comment by K0cmoc** [comment]
Try to change containers to linux. Docker icon in tray - Switch to linux containers...
