### ISSUE TITLE
Run in docker stack

### ISSUE THREAD

**Issue by luizjr** [phpdocker-io/phpdocker.io#215]
I need run in Docker Swarm, but php-fmp5.6 not install php extensions inside folder phpdocker/php-fpm/Dockerfile.

**Comment by luispabon** [comment]
I'm going to need a lot more information than that.

**Comment by luizjr** [comment]
> I'm going to need a lot more information than that.

The atribute build and context not alowe/used in docker stack

**Comment by luispabon** [comment]
Of course, you'll need to build your containers and push them to a container repository then use them in swarm.

This is not really a phpdocker.io issue, so closing.
