### ISSUE TITLE
Is there a plan to support the swoole extension?

### ISSUE THREAD

**Issue by Paccco** [phpdocker-io/phpdocker.io#216]
As the title, I need to use swoole, but I don't know how to install it in docker. Thanks！！

**Comment by luispabon** [comment]
Thank you. I'm very short of time atm to update the site with swoole support, but I've set up the base image it will use once it's in place:

https://hub.docker.com/repository/docker/phpdockerio/php74-swoole

In the meantime, you can morph a phpdocker generated environment to use that image:

  * Generate a php7.4 environment in phpdocker.io and put in your project. Don't start it yet
  * Remove the webserver nginx container from docker-compose.yaml
  * Change `FROM phpdockerio/php74-fpm` to `FROM phpdockerio/php74-swoole` in `phpdocker/php-fpm/Dockerfile`
  * Tweak the php-fpm container definition in docker-compose as follows: 
    - add a port mapping of `xxxx:xxxx` depending on what port your swoole server runs on
    - Add a `command` entry, like so `command: ["php", "/workdir/path-to-your-front-controller.php"]`

Then you can start the environment.
