### ISSUE TITLE
please support PHP 7.4 

### ISSUE THREAD

**Issue by avierr** [phpdocker-io/phpdocker.io#219]

**Comment by luispabon** [comment]
We have already php 7.4 images you can manually switch to, if you like. The reason it's not yet on site is because certain php extensions aren't yet available and still install their 7.3 counterparts. 

If you want to try this now and you already have already a working environment, try swapping `3` for `4 ` on your `phpdocker/php-fpm/Dockerfile` file, then

```
docker-compose stop php-fpm
docker-compose rm php-fpm
docker-compose build php-fpm
docker-compose up -d
```

**Comment by luispabon** [comment]
Version available today (builds daily):
```
~ docker run phpdockerio/php74-fpm php --version    
PHP 7.4.0RC6 (cli) (built: Nov 19 2019 18:13:12) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0RC6, Copyright (c), by Zend Technologies
```

**Comment by avierr** [comment]
That's awesome. Thank You!

**Comment by luispabon** [comment]
No problemo. I expect the site will have support for it on launch day, will close this when it is so.

**Comment by avierr** [comment]
PHP 7.4 is out!!

**Comment by luispabon** [comment]
Thanks for the remainder! Changes commited and deployed.

**Comment by petemcfarlane** [comment]
Hi, I still can't see 7.4 in the drop down, do I need to do anything different? https://phpdocker.io/generator
<img width="806" alt="Screenshot 2020-01-21 at 16 51 56" src="https://user-images.githubusercontent.com/3472717/72825121-62cea380-3c6e-11ea-9baf-bd00fa68ef1d.png">

**Comment by luispabon** [comment]
Hmm it is possible somehow your browser is caching an old version?

![image](https://user-images.githubusercontent.com/6388823/72826515-e7222600-3c70-11ea-9f14-3de6b2ffe2a6.png)

Try force-reloading or a different browser?

**Comment by petemcfarlane** [comment]
Ha, whatever the problem was, I'm happy to say it's gone now. I don't think it was cached as I recently switched to a different browser... but thanks for the help anyway :)

**Comment by luispabon** [comment]
![image](https://user-images.githubusercontent.com/6388823/72826965-c8705f00-3c71-11ea-85db-6146ff7c649c.png)
