### ISSUE TITLE
Can't connect to mysql server

### ISSUE THREAD

**Issue by svanschu** [phpdocker-io/phpdocker.io#225]
I pulled a setup with php 7.4, mariadb 5.5

I created the public folder and put Joomla into it. If I try to install it, I always get the error: "Can't connect to MySql Server"

In the readme file is written, that the application can connect via `localhost`.

I tried localhost, localhost:5558 and localhost:3306, but I always get the same error. What am I doing wrong here?

Host is linux. The files aren't changed.

The public folder and files have the user and group of the host user.

**Comment by luispabon** [comment]
Hi. The README file has separate portions on how to connect from outside your contianer environment, or inside. Please have a good read.

**Comment by svanschu** [comment]
Damn now I get it, I need mariadb:3306 

Sorry

**Comment by luispabon** [comment]
;)
