### ISSUE TITLE
write access for application/public folder

### ISSUE THREAD

**Issue by svanschu** [phpdocker-io/phpdocker.io#227]
Hi,
I read the readme now multiple times and searched the issues.
 
I read the issue  #154 and I looked at the https://hub.docker.com/_/nginx, which says that the nginx:alpine is running with: uid=101(nginx) gid=101(nginx) groups=101(nginx)

I'm trying to find the right userid/groupid that the webserver can habe write access to the application/public folder.

public folder with owner to be my host user --> server doesn't have write access
Setting files to 101:101 (`sudo docker exec -it sitemap-dev-webserver chown -R nginx:nginx /application/public`) --> server does'nt have write access

Which part am I missing?
This could be interesting for the readme or tutorial section  #204

**Comment by luispabon** [comment]
So you need to concentrate on the php-fpm container in fact, if you want to process file uploads. nginx does very little on this setup.

The php container runs fpm at id `33` as you can see here:

```
 ~/P/phpdocker > docker-compose exec php-fpm ps aux  
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0 452812 25820 ?        Ss   11:51   0:01 php-fpm: mast
www-data       6  0.0  0.1 459816 44224 ?        S    11:51   0:01 php-fpm: pool
www-data       7  0.0  0.1 458000 36384 ?        S    11:51   0:01 php-fpm: pool
root          21  0.0  0.0  34400  2764 pts/0    Rs+  17:03   0:00 ps aux
 ~/P/phpdocker >  docker-compose exec php-fpm id -u www-data 
33
 ~/P/phpdocker >  docker-compose exec php-fpm id -g www-data   
33
```

**Comment by svanschu** [comment]
Oh man, I tried the right things on the wrong container. 
Thank you.
This hint would be usefull for README, FAQ or something like that.

**Comment by luispabon** [comment]
No problemo :+1: happy to help

> This hint would be usefull for README, FAQ or something like that.

Absolutely. If you could put it into words and have a few minutes, I would appreciate it if you could open a pull request to the README template used in the generator with how you made it work. It doesn't have to be perfect.
