### ISSUE TITLE
symbolic links in public folder

### ISSUE THREAD

**Issue by svanschu** [phpdocker-io/phpdocker.io#229]
Does the server container oder php container have to be setup to follow symlinks?

**Comment by luispabon** [comment]
Symlinks should work, as long as the destination file exists on the container and the path on the symlink points to the same place.

**Comment by svanschu** [comment]
In public/phpAPP/administrator/components i have a symlink called com_xyz which point to home/user/projects/etc/administrator/components/com_xyz
I even gave com_xyz www-data user and group, but the phpApp don't sees it

**Comment by luispabon** [comment]
does `home/user/projects/etc/administrator/components/com_xyz` exist in the container?

**Comment by svanschu** [comment]
hmm I didn't add it as a volume.
so I would need to add this folder structure as a volume and create a symlink which exists inside the container

**Comment by svanschu** [comment]
Ok you nailed it -.- embarrassing

**Comment by luispabon** [comment]
:ok_hand:
