### ISSUE TITLE
Add help to generator

### ISSUE THREAD

**Issue by luispabon** [phpdocker-io/phpdocker.io#23]
We need to add a mechanism to provide with help on each generator field. Perhaps a "?" symbol which when hovered shows a tooltip?

**Comment by mmi-rperez** [comment]
Hi @luispabon that would be great and very helpful. If you like I can contribute to this project on my free time and help you to change a few stuff (mostly look and feel). I did know Symfony (I think project is built on top of it) so I think I can help and you can help me as well. Ping me at reynierpm in Hangouts so we can talk a bit.

**Comment by luispabon** [comment]
Hey reynier, thank you for your offer. As you can see I'm indeed a lousy visual designer, I can certainly do with help visually or otherwise. I'll try get you at hangouts, but please do feel free to fork the repo and hack away in the meantime :+1:

**Comment by reypm** [comment]
@luispabon if you need a designer I am not your guy I just would prettify a bit using Bootstrap or any other framework and yes I will fork the repo this night and work on it. Be in touch oh BTW the other user is from my work, lol my mistake

**Comment by luispabon** [comment]
That works for me :+1: Already using bootstrap at a basic level, feel free to hack about whatever you need.
