### ISSUE TITLE
Help PHP 8.0 Support

### ISSUE THREAD

**Issue by deoliveiralucas** [phpdocker-io/phpdocker.io#239]
Hi,

Do you need help to add support for PHP 8.0? I've implemented it locally, it's working, but it still have some extensions problems, for exemple to install `php-mongodb`.

Here is what I did:
https://github.com/phpdocker-io/phpdocker.io/compare/master...deoliveiralucas:php80?expand=1

If it is useful and you need something more to be implemented, please let me know that maybe I could help with this, also I can open a PR for this branch that I've created.

Tks. :)

**Comment by luispabon** [comment]
Apologies for the delay. I created the php8 images ages ago but life got on the way of me updating the site. Thanks for the code, I've been able to reuse a big chunk of it.

There's now full PHP 8 support on the generator. The mongodb extension is available for installation - I'll close this for now but please open a new issue if there's a problem to get it working.

Closed via https://github.com/phpdocker-io/phpdocker.io/pull/244
