### ISSUE TITLE
Add phpPgAdmin

### ISSUE THREAD

**Issue by luispabon** [phpdocker-io/phpdocker.io#25]
Users can now simply login into their psql container, but going into the containers is a bit of a PITA.
- Must use our PHP-FPM container base, but be separate of the app's container. This should bring down deployment time
- Instead of running PHP-FPM on said container, run PHP's built in webserver
- Consider making a base image out of this

**Comment by flolivaud** [comment]
> Maybe we can add adminer... working for mysql and postgresql !
see #24
