### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by suth** [phpdocker-io/phpdocker.io#308]
Just wanted to share the it seems like the phpdocker.io site has been timing out for the past day or two.

Appreciate this project, thanks for making it easy to run locally even when the site is offline.

**Comment by luispabon** [comment]
Thanks for letting me know. These days I host the site on a Raspberry PI off my home connection and there was a power cut. Turns out the case I'm using has a jumper for "always on" I hadn't flipped and the box never booted up once power was restored. It's all good now.
