### ISSUE TITLE
Drivers SQL Server

### ISSUE THREAD

**Issue by MagnoAlberto** [phpdocker-io/phpdocker.io#318]
I would like to suggest the possibility of including the inclusion of SQL Server drivers, I clearly know that it is possible to include later, and or even, add to the Dockerfile, but I believe that those who do not yet know the use of docker, will require good hours of research to include the drivers in the container.

_ps: Thanks for the excellent tool. It was very helpful to understand docker better._

**Comment by luispabon** [comment]
Thanks @MagnoAlberto for the suggestion, but the choice of not adding more extensions into the base image is deliberate. You are meant to install only what you are going to use.
