### ISSUE TITLE
[feature] Vips and PHP Vips

### ISSUE THREAD

**Issue by jarodium** [phpdocker-io/phpdocker.io#319]
Hello 

I would like to suggest VIPS and php vips support to be enabled.

**Comment by luispabon** [comment]
Please make a feature request here https://github.com/oerdnj/deb.sury.org (this is where we get our php packages from) and link back here for me to update the site once it's available.

**Comment by jarodium** [comment]
@luispabon 

Thank you for your time. Issue [posted](https://github.com/oerdnj/deb.sury.org/issues/1843)
