### ISSUE TITLE
PHP 8.2 image does not include my specified optional components

### ISSUE THREAD

**Issue by realj42** [phpdocker-io/phpdocker.io#334]
I am trying to create a PHP8.2  stack with a number of  optional libraries but none of them are being included in the final build, crucially phpp8.2-mysql is missing.  I have tried to rebuild multiple times but no luck ,  The contents of my Dockerfile are 

FROM phpdockerio/php:8.2-fpm
WORKDIR "/application"

RUN apt-get update; \
    apt-get -y --no-install-recommends install \
        php8.2-bcmath \ 
        php8.2-gd \ 
        php8.2-gmagick \ 
        php8.2-imagick \ 
        php8.2-mysql \ 
        php8.2-xdebug; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
------

None of these install libraries are included - checked by running phpinfo.

**Comment by luispabon** [comment]
Your second post is wrong, looks like you're trying to run `php8.2-gd` and all the others for instance directly on the shell.

After you update your Dockerfile, you need to 

```
docker-compose build php-fpm
docker-compose down php-fpm
docker-compose up -d
```

It's on the README generated alongside the zip file.

**Comment by realj42** [comment]
Hi - I am afraid your fix does not work - the optional  libraries are simply not getting installed, no matter how many times I try to build the image.  For now I will switch to using the bitnami/php-fpm image as that does include all libraries as standard.
