### ISSUE TITLE
Windows 11 alert that phpdocker.zip is a virus

### ISSUE THREAD

**Issue by btoms** [phpdocker-io/phpdocker.io#336]
Hello

Windows 11 alert that download phpdocker.zip is a virus (downloaded from https://phpdocker.io/)

I select php 8.1, add git option and mysql, and some common php modules (mysql, SQLite3, ssh, soap, raph, mongodb GD...)

can you check this issue?

![image](https://user-images.githubusercontent.com/14225328/221463113-ebafc242-1d73-4e42-8a66-92e42e9d19fc.png)

thanks in advance!
I really appreciate your work

**Comment by luispabon** [comment]
Not much I can do about it if the antivirus doesn't actually analyse the html file I'm afraid 🤷 which antivirus is it? windows defender?

**Comment by btoms** [comment]
Yes it's windows defender

It happens when wehen I enable some of the current "services"

-  mysql 
- maria
-  postgre
-  elastic search  

With zero config services happens when enable 

- Memcached 
- Mailhog 
- Clickhouse

But doesn't happen when only enable Redis without any thing more

Sorry for the late response

**Comment by luispabon** [comment]
That's truly bizarre, the only difference on the README with any of those options enabled is a table that contains links to them. HTML links. I don't really have a windows computer to check though, is there any way you could clone the repo and run the site locally? Then tweak the HTML template to see what exactly is tripping up windows defender.

**Comment by btoms** [comment]
Hello Luis

Bad news, I finally get phpdocker.io working under my windows ( https://localhost:10000/)  

But I see that windows trust anything that comes from localhost, and zip are trusted as "free of virus" because comes from my localhost

I tried too to upload the phpdocker.zip from my localhost to google drive, and download again. But windows don't detect it as a "virus"

The problem for windows comes from html readme (README.html)

I think that can: 

- report to Microsoft the false positive:
  (See here) https://answers.microsoft.com/en-us/windows/forum/all/windows-defender-bug-detects-javascript-files-as/c8a2c595-6a54-4b2e-a0b5-6aa0f8f536a3
- remove links or remove readme.html
 ( only from README.html )
- remove  README.html entirely?
- forget windows users, but there are a lot windows users  ... :D

Thanks
