### ISSUE TITLE
Clickhouse is being added whenever Memcached is selected

### ISSUE THREAD

**Issue by djozsef** [phpdocker-io/phpdocker.io#342]
When Memcached Zero-Config Service is selected (with none other options selected) Clickhouse get added as a service into docker-compose.yml. 

The root cause is a wrong condition chech at https://github.com/phpdocker-io/phpdocker.io/blame/4cc009816a79de0f5dfa01c61102fe5508c1530a/src/PHPDocker/Generator/Files/DockerCompose.php#L184

**Comment by luispabon** [comment]
Thanks for your fix
