### ISSUE TITLE
mysqli extension is missing

### ISSUE THREAD

**Issue by maksymenkoml** [phpdocker-io/phpdocker.io#349]
Even after selecting all extensions, it's still missing the `mysqli` extension.
For example, Wordpress is not working.
```# php -m
[PHP Modules]
apcu
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
PDO
Phar
posix
random
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

<img width="864" alt="image" src="https://github.com/phpdocker-io/phpdocker.io/assets/122663362/8c760ef2-3f00-4039-b830-b7e1c144dd85">

**Comment by luispabon** [comment]
I can't help you without your docker files.

**Comment by maksymenkoml** [comment]
Docker files were generated from your website, and I didn't modify anything in them.
You can just select PHP 8.2 (for example), select all modules, MySQL, and try.

**Comment by luispabon** [comment]
I still need to see your files or I won´t be able to help you.

**Comment by maksymenkoml** [comment]
[Archive.zip](https://github.com/phpdocker-io/phpdocker.io/files/11907843/Archive.zip)

**Comment by luispabon** [comment]
Thank you. The problem is this:

![image](https://github.com/phpdocker-io/phpdocker.io/assets/6388823/14bbb115-f7b7-47fe-bb95-76b1047ccf03)

You need to choose either `php8.2-gmagick` or `php8.2-imagick` but not both on your Dockerfile.

Incidentally the docker build should have failed to highlight this error, this I can fix.

**Comment by maksymenkoml** [comment]
Thank you for the quick fix. Now it's working.
