### ISSUE TITLE
Generator | Add Silex in Application type

### ISSUE THREAD

**Issue by Keirodev** [phpdocker-io/phpdocker.io#61]
Because the nginx configfile is different for Silex than Symfony.
See [this example](http://silex.sensiolabs.org/doc/master/web_servers.html#nginx) from Silex doc.

**Comment by luispabon** [comment]
Hi @Keirodev , thank you for your report. Could you please check whether it works with the generic application type at all?

**Comment by Keirodev** [comment]
Hi there,
I first try the generic ;)
Unfortunately iit seems that neither the SF one nor the generix worked.

**Comment by luispabon** [comment]
Understood, I'll have a look asap :+1:

**Comment by luispabon** [comment]
Sorry for the delay. Silex should now be working correctly.
