### ISSUE TITLE
Redis: Fix kernel configuration warning

### ISSUE THREAD

**Issue by denudge** [phpdocker-io/phpdocker.io#65]
After creating a redis container, the following warning is displayed:

WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.

**Comment by luispabon** [comment]
:+1:

**Comment by luispabon** [comment]
After some investigation, turns out this needs doing on the host, not within the container:

https://github.com/docker-library/redis/issues/55

Looks unavoidable.
