### ISSUE TITLE
Add support for Node.js

### ISSUE THREAD

**Issue by denudge** [phpdocker-io/phpdocker.io#66]
Every web project needs some kind of frontend. If you're thinking of "modern" web frontends, there will be always the need for Node.js, be it for babel, tsc, gulp, webpack, sass or whatever.

This container should either offer multiple entrypoints to run a specific tool, or be shell accessable.

**Comment by luispabon** [comment]
I'd be happy to implement this but at the moment I lack examples, do you have anything handy that covers multiple entry points?

**Comment by enzoclock** [comment]
@luispabon Hi Luis ! 
I came across this very useful tool (thanks!) and wonder if, by any chance, you know a similar tool centered around Node.js/JS. 

This post thread is 6 years old, so I'm curious to know if something has popped up in the meantime :) 
Found [this](https://www.npmjs.com/package/dockerfile-generator), but lacking the UI. I might contribute there if nothing comes to your mind ! 

Thanks !

**Comment by luispabon** [comment]
No, nothing ever came out of this. Node is a beast of its own to be fair with many different use cases, so I never went down that route. But I'm always happy to accept contriutions
