### ISSUE TITLE
Add git to PHP docker for composer update

### ISSUE THREAD

**Issue by Mondane** [phpdocker-io/phpdocker.io#69]
When running *composer update* it can be necessary to have Git available:

>  - Updating friendsofsymfony/user-bundle dev-master (28151dc => 03ce036)
>    Update failed (Failed to execute git show-ref --head -d
>
>sh: 1: git: not found
>)
>    Would you like to try reinstalling the package instead [yes]? yes
>  - Removing friendsofsymfony/user-bundle (dev-master)
>
>                                            
>  [RuntimeException]                        
>  Failed to execute git show-ref --head -d  
>  sh: 1: git: not found                     

Would be good to add this to the *docker-compose.yml* .

On a side-note, it's best to run composer update as user *www-data* so the vendor map gets the correct user set.

**Comment by flolivaud** [comment]
Maybe the right way is to have a composer container with git installed ?

**Comment by luispabon** [comment]
The problem with adding in git is it adds perl in and extra 70MB just in the off chance of using dev dependencies, and not everybody is up for this. I'll add it as an extra option to the generator.

**Comment by siran** [comment]
Yeah, I needed this too. It still doesn't appear in the generator : (

**Comment by DracoBlue** [comment]
Actually I think in a development box, its quite common to have dev dependencies ;).

An option for this would be greatly appreciated, too!

**Comment by luispabon** [comment]
I've added this feature to the generator, and it's online at https://phpdocker.io/generator 

Would be great if you guys could give it a spin and let me know how it works for you :+1:
