### ISSUE TITLE
PHP 7.0 FPM container doesn't start service

### ISSUE THREAD

**Issue by SniperSister** [phpdocker-io/phpdocker.io#70]
Hi,

I'm setting up a new development project right now and therefore I generated phpdocker fileset. While running
> docker-compose up -d

I run into the following error message

> ERROR: for foobar-webserver  Cannot start service foobar-webserver: Cannot link to a non running container: /foobar-php-fpm AS /foobar-webserver/foobar-php-fpm
> ERROR: Encountered errors while bringing up the project.

Apparently the FPM container doesn't start the FPM process. If I take a look into the list of containers (docker ps -a) I get the following last run command for the container:

> "/bin/sh -c '#(nop) WORKDIR /var/www/foobar'"

An phpdocker environment that I have build earlier this month shows this command:

> "/bin/sh -c '/usr/sbin/php-fpm7.0 -F -O 2>&1 | sed -u 's,.*: \\\"\\(.*\\)$,\\1,'| sed -u 's,\"$,,' 1>&1'" 

Any idea why the new environment runs the wrong command and so doesn't start the service?

**Comment by luispabon** [comment]
That's bizarre, could you please post the zip file you got off the generator so that I can give it a shot?

**Comment by SniperSister** [comment]
After replacing "WORKDIR "/var/www/foobar" with the original CMD from the php7-fpm container Dockerfile it's now working fine. Apparently the current Docker for Mac version doesn't execute the CMD of a parent image?!

**Comment by SniperSister** [comment]
Sure, here we go: 
[phpdockerio.zip](https://github.com/phpdocker-io/phpdocker.io/files/652273/phpdockerio.zip)

**Comment by luispabon** [comment]
Thank you for the file :+1: Just tried this on latest "native" docker on a Mac as well as on Vagrant and the project started up fine. I'm not sure what to make of it other than some sort of docker-mac weirdness. Are you fully up to date?

**Comment by SniperSister** [comment]
Yes, just updated to the latest Docker of Mac version, same problem

**Comment by luispabon** [comment]
Very weird. Tried `vagrant up` see if the error is also in there?

**Comment by webremote** [comment]
FYI, yesterday everything worked fine, today i'm getting this: `ERROR: for php-fpm  Cannot start service php-fpm: Container command '/bin/sh' not found or does not exist.`
