### ISSUE TITLE
Docker-Compose v2/v3

### ISSUE THREAD

**Issue by flolivaud** [phpdocker-io/phpdocker.io#80]
Enhance docker-compose.yml in version 2 / 3.

[DOC](https://docs.docker.com/compose/gettingstarted/)

**Comment by luispabon** [comment]
Done and released :+1:

**Comment by flolivaud** [comment]
Thanks. I'll try to contribute to issues when i have more time.

**Comment by luispabon** [comment]
Much appreciated.
