### ISSUE TITLE
Readme notice of supported containers may be incorrect?

### ISSUE THREAD

**Issue by viion** [phpdocker-io/phpdocker.io#82]
Once a docker zip has been generated, the read me states:

`MacOS and Windows have no native support for docker containers.`

I do not think this is the case anymore. Using [Docker CE](https://www.docker.com/community-edition) I was able to run `docker-compose up` and have an environment running in docker containers on MacOS.

Have not tested in Windows but they supply an application for it, so I assume it works!

**Comment by luispabon** [comment]
The readme has indeed been neglected, I've been meaning to update it (and remove the vagrant option) for a while but work is getting in the way. Thanks for the reminder!
