### ISSUE TITLE
Phalcon now supports 7.1 - Option needs allowing.

### ISSUE THREAD

**Issue by viion** [phpdocker-io/phpdocker.io#83]
Not urgent.

Source: https://blog.phalconphp.com/post/phalcon-3-1-2-released-php7-1-support

*quote:*

## PHP 7.1 Support
> Fixed PHP 7.1 issues #12055.

This issue took us a lot longer to address than we would have liked. We had to tackle issues with Zephir as well as our code generation scripts along with this one.
The wait is over though! Phalcon can be installed with PHP 7.1 installations, so enjoy it!

**Comment by luispabon** [comment]
Thank you, I'll work on enabling and testing this ASAP :+1:

**Comment by luispabon** [comment]
This is done and released :+1:
