### ISSUE TITLE
No MTA installed (sendmail not found) with PHP FPM

### ISSUE THREAD

**Issue by aland** [phpdocker-io/phpdocker.io#95]
I thought that with Mailhog being bundled, there would be some integration out of the box, but using php mail() functions result in ` /usr/sbin/sendmail: not found` being logged.

Would it make sense to include exim4 in the php-fpm container configured to use mailhog?

**Comment by luispabon** [comment]
You need to configure your mailer to SMTP into mailhog, in this case mailhog would be your MTA.

**Comment by aland** [comment]
Thanks but PHP's [mail()](http://php.net/manual/en/function.mail.php) functions don't support SMTP directly (except on Windows).

I'll take it as motivation to move to a better mail library, like [PHPMailer](https://github.com/PHPMailer/PHPMailer).

**Comment by luispabon** [comment]
Ahh definitely, there are much better ways to send emails these days. SwiftMailer is pretty good as well. Both would allow you to SMTP.

**Comment by luispabon** [comment]
I don't believe there is, unless you hijack the system's sendmail command to SMTP.

**Comment by zack6849** [comment]
@luispabon you can in fact do this, though it's not technically sendmail, you'd need to use mhsendmail, see my repo here:

https://github.com/zack6849/yapi/blob/master/php/Dockerfile#L11
https://github.com/zack6849/yapi/blob/master/php/mailhog.ini

**Comment by luispabon** [comment]
Thanks  @zack6849 :+1: hope this is useful to somebody that stumbles upon this ticket.
